[package]
name = "miow"
version = "0.3.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["iocp", "windows", "io", "overlapped"]
repository = "https://github.com/alexcrichton/miow"
homepage = "https://github.com/alexcrichton/miow"
documentation = "https://docs.rs/miow/0.1/x86_64-pc-windows-msvc/miow/"
description = """
A zero overhead I/O library for Windows, focusing on IOCP and Async I/O
abstractions.
"""

[dependencies]
net2 = { version = "0.2.5", default-features = false }

[dependencies.winapi]
version = "0.3.2"
features = [
  "std",
  "fileapi",
  "handleapi",
  "ioapiset",
  "minwindef",
  "namedpipeapi",
  "ntdef",
  "winerror",
  "winsock2",
  "ws2def",
  "ws2ipdef",
]

[dev-dependencies]
rand = "0.4"
